// SPDX-License-Identifier: MIT
pragma solidity 0.8.35;

import {Clones} from "@openzeppelin/contracts/proxy/Clones.sol";

/// Cross-checks the off-chain backend's computeDepositAddress (crossmesh-ingress/src/evm/cwia.ts) against
/// OZ Clones for the `recipient ++ uint8(fast)` args layout, using a fixed factory/impl test vector.
/// DepositFactory.computeAddress makes the identical OZ call with address(this) as the deployer, so
/// backend == OZ == factory. Vectors generated by the backend's scripts/_gen-cwia-vectors.ts.
contract CwiaVectorTest {
    address constant FACTORY = 0x0E37Ba881cD1D6fAe4E26BC1a7C0D44A6Fbc028C;
    address constant IMPL = 0x0c7DEaE2DF6b9dC3993c11b62e6BDD6A308CA80e;

    function _addr(bytes memory recipient, uint256 index, bool fast) internal pure returns (address) {
        bytes memory args = abi.encodePacked(recipient, fast ? uint8(1) : uint8(0));
        bytes32 salt = keccak256(abi.encode(recipient, index));
        return Clones.predictDeterministicAddressWithImmutableArgs(IMPL, args, salt, FACTORY);
    }

    function test_backend_vectors_match_oz() public pure {
        bytes memory g = bytes("GBUKBCG5VLRKAVYAIREJRUJHOKLIADZJOICRW43WVJCLES52BDOTCQZU");
        bytes memory c = bytes("CDLZFC3SYJYDZT7K67VZ75HPJVIEUVNIXG7WP3GVQ4MV23U6AKOJVPJ4");
        bytes memory m = bytes("MA7QYNF7SOWQ3GLR2BGMZEHXAVIRZA4KVWLTJJFC7MGXUA74P7UJUAAAAAAAAAAAAACJUQ");
        require(_addr(g, 0, false) == 0x95454a3001af5FAcc60f439B6397491Fe7BDF30B, "G/0/std");
        require(_addr(g, 0, true) == 0x07054eC2792c414878C1840106e9666810dDC10C, "G/0/fast");
        require(_addr(g, 7, false) == 0xD6746898AD8d72D5B49a7dfc78D657f1FE70db3A, "G/7/std");
        require(_addr(c, 1, false) == 0x3CD2e19C6F5344573B7Dc9F26792712Ff108FbFb, "C/1/std");
        require(_addr(c, 1, true) == 0xadE8e331683585294B6834C6B78Ec9ac69653756, "C/1/fast");
        require(_addr(m, 0, false) == 0xb8476417d37244dB18B9A08a4B6379445eeFFeB2, "M/0/std");
        require(_addr(m, 0, true) == 0xA6d8ca9D2FF6b984Ea3DfbB245439624688F6917, "M/0/fast");
    }
}
